services:
    feed.parser:
        class: AppBundle\Service\FeedParser
    elasticsearch.synchronizer:
        class: AppBundle\Service\ElasticsearchSynchronizer
        arguments: ['%es_hosts%']
    elasticsearch.engine:
        class: AppBundle\Service\ElasticsearchEngine
        arguments: ['%es_hosts%']
    paginator:
        class: AppBundle\Service\Paginator
        arguments: ['@router']
