services:
    feed.parser:
        class: AppBundle\Service\FeedParser
    elasticsearch.synchronizer:
        class: AppBundle\Service\ElasticsearchSynchronizer
    elasticsearch.engine:
        class: AppBundle\Service\ElasticsearchEngine
